### ISSUE TITLE
Categories/topics on data cataogue page needs to be clickable into an archive of all datasets that use that topic/category

### ISSUE THREAD

**Issue by sidramatik** [CityofToronto/wp-open-data-toronto#28]

**Comment by yizhaotanTO** [comment]
Removed the tags on catalogue page for topics, from testing user did not interact with the card itself at all. Does this issue still apply?

**Comment by careduz** [comment]
based on discussions yesterday, my understanding is that we would include the heading and value for every filter (including Topic), we can revisit this if we have an array of metadata we want to show. Topic was listed alongside the other metadata fields as part of addressing issue #36, closing as legacy item.
