### ISSUE TITLE
All inputs require labels on page-catalogue.php

### ISSUE THREAD

**Issue by sidramatik** [CityofToronto/wp-open-data-toronto#32]
In page-catalogue.php, `<input>` requires an associated `<label>`. This is currently missing in:
1. Search Datasets search bar
2. "Show more" list group cannot be empty; the label still appears but it's empty. 
3. No label on search icon for Search Datasets search bar (buttons count as inputs!)

**Comment by yizhaotanTO** [comment]
1. Moved label to the correct place
2. Resolved this from another issue
3. Added label

Need validation if this is done correctly

**Comment by sidramatik** [comment]
Should be resolved now; still need to confirm if "View 10 more" labels are AT-appropriate.
