### ISSUE TITLE
Refresh headings in semantic order on catalogue page 

### ISSUE THREAD

**Issue by sidramatik** [CityofToronto/wp-open-data-toronto#39]
Current:
![image](https://user-images.githubusercontent.com/498765/49025432-a5c7e080-f169-11e8-8d67-40763e9af1c1.png)

**Comment by sidramatik** [comment]
Recommended:

(h1) Open Data Catalogue - (aka the_title();)
  (h2) Datasets
    (h3) Bicycle Shops
    (h3) On-Street Permit Parking
    (h3) Doors Open Toronto
  (h2) Filters
    (h3) Topic
    (h3) Publisher
    (h3) Type
    (h3) Format

**Comment by careduz** [comment]
Related to comment in Issue #31 , there are no H2s (Datasets, Filters) but made the other changes

**Comment by sidramatik** [comment]
Will add H2 for screen reader only.
