### ISSUE TITLE
Consider if we need both TYPE and DOCUMENT on the data catalogue page; seems redundant

### ISSUE THREAD

**Issue by sidramatik** [CityofToronto/wp-open-data-toronto#41]
![image](https://user-images.githubusercontent.com/498765/49026248-600c1780-f16b-11e8-9a11-5f0bdd69881f.png)

**Comment by sidramatik** [comment]
Should reflect filters; topic would work well here.

**Comment by careduz** [comment]
based on discussions yesterday, my understanding is that we would include the heading and value for every filter (including Topic). This has been done when addressing issue  #36.

**Comment by sidramatik** [comment]
Works for me!
