### ISSUE TITLE
"Show 10 more" text doesn't change in sidebar when full list of filters is expanded

### ISSUE THREAD

**Issue by sidramatik** [CityofToronto/wp-open-data-toronto#43]
- ![image](https://user-images.githubusercontent.com/498765/49245144-7ae6c200-f3df-11e8-8564-987fa39c7eea.png)

- Change [+] 10 more to "Show 10 more", or "Show 10 more topics"
 
- Will likely require some supportive title text for Assistive Technologies: how about:
`<a href="#">Show 10 more<span class="sr-only">topics</span></a>`

**Comment by sidramatik** [comment]
+ change for collapse to "Collapse [sr-only]expanded list of topics[/sr-only]"?

**Comment by careduz** [comment]
Also fixed: now updates to "Collapse", it was staying at "[+] 10 more".
